name: vae-rs
channels: 
  - conda-forge
  - defaults
dependencies:
  - numpy
  - rasterio
  - tqdm
  - matplotlib
  - polars
  - pre-commit
  - scikit-image
  - optuna
  - optuna-dashboard
  - pip
  - pip:
      - torch
      - tensorboard
      - standard-imghdr
      - lpips