name: uv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: uv
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install deps
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync deps
        run: |
          uv sync && uv venv
