name: uv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: uv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install deps
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip download \
            --only-binary=:all: \
            --platform manylinux2014_x86_64 \
            --implementation cp \
            --abi cp313 \
            --python-version 3.13 \
            .
